fastlane_version '2.221.0'
default_platform :ios

platform :ios do
  before_all do
    setup_ci
  end

  desc 'Builds project and executes unit tests'
  lane :tests do
    run_tests(workspace: "#{ENV['APP_XCODEPROJ']}/project.xcworkspace",
              devices: ["iPhone 15 Pro"],
              scheme: "#{ENV['APP_SCHEME']}")
  end

  lane :test_flight do
    api_key = app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_API_PRIVATE_KEY']}",
      issuer_id: "#{ENV['APP_STORE_API_KEY_ISSUER_ID']}",
      key_filepath: "#{ENV['APP_AUTH_KEY_FILEPATH']}",
      duration: "#{ENV['APP_STORE_CONNECT_DURATION']}" 
    )
    previous_build_number = latest_testflight_build_number(
      app_identifier:"#{ENV['APP_IDENTIFIER']}",
      api_key: api_key,
    )
    
    current_build_number = previous_build_number + 1
    increment_build_number(
      xcodeproj: "#{ENV['APP_XCODEPROJ']}",
      build_number: current_build_number
    )

    sync_code_signing(
      type: "appstore",
      readonly: true,
    )

    build_app(
      scheme: "#{ENV['APP_SCHEME']}",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    ) 
  end
end

