name: Pull Request

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  CI:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.KEY }}
        
      - uses: maxim-lobanov/setup-xcode@v1
        id: setup-xcode
        with:
          xcode-version: latest-stable
        
      - name: Set up Ruby
        id: setup-ruby
        uses: ruby/setup-ruby@v1

      - name: Install Bundler
        id: install-bundler
        run: gem install bundler

      - name: Install gems
        id: install-gems
        run: bundle install

      - name: Swift Packages Cache
        id: swift-packages-cache
        uses: actions/cache@v2
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-
    
      #https://github.com/futureware-tech/simulator-action/wiki
      - name: Launch Simulator
        uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15 Pro'
          os: 'iOS'
          os_version: '17.2'

      - name: Run Tests (No Cache)
        if: steps.setup.outputs.cache-hit != 'true'
        run: bundle exec fastlane tests
      
      - name: Run Tests (Cache)
        if: steps.setup.outputs.cache-hit == 'true'
        run: bundle exec fastlane tests skip_package_dependencies_resolution:true
  CD:
    needs: CI
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.KEY }}
        
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        
      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install
      
      - name: Send to TF
        run: bundle exec fastlane test_flight